import { writeFile } from "node:fs/promises";
import path from "node:path";
import type { BlogPost } from "../src/types/blog";
import type { Product, ProductOverride } from "../src/types/product";

type ProductRow = {
  slug: string;
  image_url: string | null;
  content: Product & { description?: string };
};
type BlogRow = { content: BlogPost };

const url = process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!url || !serviceKey) {
  console.log("cms:sync skipped (Supabase build secrets are not configured)");
  process.exit(0);
}
const buildUrl = url;
const buildKey = serviceKey;

async function readRows<T>(table: string): Promise<T[]> {
  const response = await fetch(
    `${buildUrl}/rest/v1/${table}?status=eq.published&select=*&order=updated_at.desc`,
    { headers: { apikey: buildKey, Authorization: `Bearer ${buildKey}` } }
  );
  if (!response.ok) throw new Error(`CMS sync failed for ${table}: ${response.status}`);
  return (await response.json()) as T[];
}

const [productRows, blogRows] = await Promise.all([
  readRows<ProductRow>("cms_products"),
  readRows<BlogRow>("cms_blog_posts"),
]);

const products = productRows.map((row) => row.content);
const posts = blogRows.map((row) => row.content);

// Fail the deployment instead of publishing malformed dynamic routes.
for (const product of products) {
  if (!product.slug || !product.name || !Array.isArray(product.finishes) || !Array.isArray(product.applicationIndex)) {
    throw new Error(`Invalid published product payload: ${product.slug || "missing-slug"}`);
  }
}
for (const post of posts) {
  if (!post.slug || !post.title || typeof post.bodyHtml !== "string") {
    throw new Error(`Invalid published blog payload: ${post.slug || "missing-slug"}`);
  }
}
const overrides = Object.fromEntries(
  productRows.map((row) => [
    row.slug,
    {
      imageUrl: row.image_url ?? undefined,
      imageUrls: row.image_url ? [row.image_url] : undefined,
      description: row.content.description,
    } satisfies ProductOverride,
  ])
);

const root = process.cwd();
const generatedBanner = "// Generated by scripts/sync-cms-data.ts. Do not edit manually.\n";
await Promise.all([
  writeFile(
    path.join(root, "src/data/cms-products.generated.ts"),
    `${generatedBanner}import type { Product } from "@/types/product";\nexport const CMS_PRODUCTS: Product[] = ${JSON.stringify(products, null, 2)};\nexport const CMS_PRODUCTS_SYNCED = true;\n`
  ),
  writeFile(
    path.join(root, "src/data/cms-blog.generated.ts"),
    `${generatedBanner}import type { BlogPost } from "@/types/blog";\nexport const CMS_BLOG_POSTS: BlogPost[] = ${JSON.stringify(posts, null, 2)};\nexport const CMS_BLOG_POSTS_SYNCED = true;\n`
  ),
  writeFile(
    path.join(root, "src/data/cms-product-overrides.generated.ts"),
    `${generatedBanner}import type { ProductOverride } from "@/types/product";\nexport const CMS_PRODUCT_OVERRIDES: Record<string, ProductOverride> = ${JSON.stringify(overrides, null, 2)};\n`
  ),
]);

console.log(`cms:sync wrote ${products.length} products and ${posts.length} blog posts`);
