// This file is auto-generated by scripts/build-product-data.ts. Do not edit.
import type { ProductCategories } from "@/types/product";

export const PRODUCT_CATEGORIES: ProductCategories = {
  "materials": [
    {
      "name": "Bluestone",
      "slug": "bluestone"
    },
    {
      "name": "Granite",
      "slug": "granite"
    },
    {
      "name": "Limestone",
      "slug": "limestone"
    },
    {
      "name": "Marble",
      "slug": "marble"
    },
    {
      "name": "Permeable Paver",
      "slug": "permeable-paver"
    },
    {
      "name": "Porcelain",
      "slug": "porcelain"
    },
    {
      "name": "Quartz",
      "slug": "quartz"
    },
    {
      "name": "Reclaimed Brick",
      "slug": "reclaimed-brick"
    },
    {
      "name": "Sandstone",
      "slug": "sandstone"
    },
    {
      "name": "Travertine",
      "slug": "travertine"
    }
  ],
  "applications": [
    {
      "name": "Cladding",
      "slug": "cladding",
      "subtypes": [
        {
          "name": "Corner Return",
          "slug": "corner-return"
        },
        {
          "name": "Wall Cladding",
          "slug": "wall-cladding"
        }
      ]
    },
    {
      "name": "Cobble Stone",
      "slug": "cobble-stone"
    },
    {
      "name": "Crazy Paver",
      "slug": "crazy-paver"
    },
    {
      "name": "Giant Stepper",
      "slug": "giant-stepper"
    },
    {
      "name": "Kerb",
      "slug": "kerb"
    },
    {
      "name": "Organic Stepper",
      "slug": "organic-stepper"
    },
    {
      "name": "Organic Table and Seat",
      "slug": "organic-table-and-seat",
      "subtypes": [
        {
          "name": "Seat",
          "slug": "seat"
        },
        {
          "name": "Table",
          "slug": "table"
        },
        {
          "name": "Table Sets",
          "slug": "table-sets"
        }
      ]
    },
    {
      "name": "Patterns",
      "slug": "patterns",
      "subtypes": [
        {
          "name": "Ashlar Pattern",
          "slug": "ashlar-pattern"
        },
        {
          "name": "French Pattern",
          "slug": "french-pattern"
        },
        {
          "name": "Herringbone Pattern",
          "slug": "herringbone-pattern"
        }
      ]
    },
    {
      "name": "Paver",
      "slug": "paver"
    },
    {
      "name": "Pitcher",
      "slug": "pitcher"
    },
    {
      "name": "Pool Coping",
      "slug": "pool-coping",
      "subtypes": [
        {
          "name": "Bevelled Edge",
          "slug": "bevelled-edge"
        },
        {
          "name": "Bull Nose",
          "slug": "bull-nose"
        },
        {
          "name": "Drop Face",
          "slug": "drop-face"
        }
      ]
    },
    {
      "name": "Slab",
      "slug": "slab"
    }
  ]
};
