// Generated by scripts/sync-cms-data.ts. Do not edit manually.
import type { LegacyPageContentMap, ManagedPage, ManagedProject } from "@/types/siteContent";
export const CMS_MANAGED_PAGES: Partial<Record<ManagedPage["key"], ManagedPage>> = {
  "home": {
    "key": "home",
    "title": "Home",
    "heroImageUrl": "/AushenShop.webp",
    "blocks": []
  },
  "services": {
    "key": "services",
    "title": "Services",
    "heroImageUrl": "/task-a-2026-02-24/svc-profiling.webp",
    "blocks": []
  },
  "about": {
    "key": "about",
    "title": "Our Story",
    "heroImageUrl": "/task-a-2026-02-24/about-hero-quarry.webp",
    "blocks": []
  }
};
export const CMS_MANAGED_PROJECTS: ManagedProject[] = [
  {
    "id": 1,
    "slug": "brighton-residence",
    "tags": [
      "Residential",
      "Pool",
      "Landscape"
    ],
    "year": "2023",
    "image": "https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=1600&auto=format&fit=crop",
    "title": "Brighton Residence",
    "aspect": "aspect-[16/10]",
    "credits": {
      "builder": "Construct Co.",
      "architect": "Studio A&D",
      "landscaper": "Green Life Designs",
      "photographer": "Timothy Kaye"
    },
    "gallery": [
      {
        "alt": "Wide shot of pool area",
        "src": "https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=2000&auto=format&fit=crop",
        "type": "full"
      },
      {
        "alt": "Detail of coping",
        "src": "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?q=80&w=1200&auto=format&fit=crop",
        "type": "half"
      },
      {
        "alt": "Top down view of pavers",
        "src": "https://images.unsplash.com/photo-1620626012053-93f2685048d6?q=80&w=1200&auto=format&fit=crop",
        "type": "half"
      },
      {
        "alt": "Exterior facade",
        "src": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2000&auto=format&fit=crop",
        "type": "full"
      }
    ],
    "category": "Residential",
    "gridArea": "left",
    "location": "Brighton, Victoria",
    "products": [
      {
        "name": "Cathedral Limestone",
        "slug": "cathedral-limestone",
        "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop",
        "category": "Limestone"
      },
      {
        "name": "Midnight Bond Pavers",
        "slug": "midnight-bond",
        "image": "https://images.unsplash.com/photo-1620626012053-93f2685048d6?q=80&w=800&auto=format&fit=crop",
        "category": "Bluestone"
      }
    ],
    "description": "A monolithic expression of raw materials. The Brighton Residence utilizes our Cathedral Limestone to blur the boundaries between interior living and poolside terrace."
  },
  {
    "id": 2,
    "slug": "toorak-pool-house",
    "tags": [
      "Residential",
      "Pool"
    ],
    "year": "2022",
    "image": "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?q=80&w=1200&auto=format&fit=crop",
    "title": "Toorak Pool House",
    "aspect": "aspect-[3/4]",
    "credits": {
      "builder": "Form Build",
      "architect": "Pierce Atelier",
      "landscaper": "South Garden Studio",
      "photographer": "Lara Finch"
    },
    "gallery": [
      {
        "alt": "Wide shot of pool area",
        "src": "https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=2000&auto=format&fit=crop",
        "type": "full"
      },
      {
        "alt": "Detail of coping",
        "src": "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?q=80&w=1200&auto=format&fit=crop",
        "type": "half"
      },
      {
        "alt": "Top down view of pavers",
        "src": "https://images.unsplash.com/photo-1620626012053-93f2685048d6?q=80&w=1200&auto=format&fit=crop",
        "type": "half"
      },
      {
        "alt": "Exterior facade",
        "src": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2000&auto=format&fit=crop",
        "type": "full"
      }
    ],
    "category": "Landscape",
    "gridArea": "right",
    "location": "Toorak, Victoria",
    "products": [
      {
        "name": "Coastal Limestone",
        "slug": "coastal-limestone",
        "image": "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?q=80&w=800&auto=format&fit=crop",
        "category": "Limestone"
      },
      {
        "name": "Saltwash Coping",
        "slug": "saltwash-coping",
        "image": "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?q=80&w=800&auto=format&fit=crop",
        "category": "Pool Coping"
      }
    ],
    "description": "A restrained material palette designed for outdoor living. Warm textured stone creates continuity from the pool edge to the terrace and internal floor plane."
  },
  {
    "id": 3,
    "slug": "mornington-peninsula-winery",
    "tags": [
      "Commercial",
      "Hospitality"
    ],
    "year": "2021",
    "image": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=1600&auto=format&fit=crop",
    "title": "Mornington Peninsula Winery",
    "aspect": "aspect-[16/9]",
    "credits": {
      "builder": "Harbor Constructions",
      "architect": "Terrain Projects",
      "landscaper": "Native Field",
      "photographer": "Michael Ward"
    },
    "gallery": [
      {
        "alt": "Wide shot of pool area",
        "src": "https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=2000&auto=format&fit=crop",
        "type": "full"
      },
      {
        "alt": "Detail of coping",
        "src": "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?q=80&w=1200&auto=format&fit=crop",
        "type": "half"
      },
      {
        "alt": "Top down view of pavers",
        "src": "https://images.unsplash.com/photo-1620626012053-93f2685048d6?q=80&w=1200&auto=format&fit=crop",
        "type": "half"
      },
      {
        "alt": "Exterior facade",
        "src": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2000&auto=format&fit=crop",
        "type": "full"
      }
    ],
    "category": "Commercial",
    "gridArea": "left",
    "location": "Mornington, Victoria",
    "products": [
      {
        "name": "Vineyard Travertine",
        "slug": "vineyard-travertine",
        "image": "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=800&auto=format&fit=crop",
        "category": "Travertine"
      },
      {
        "name": "Sawn Bluestone",
        "slug": "sawn-bluestone",
        "image": "https://images.unsplash.com/photo-1621260405282-3d76378e906c?q=80&w=800&auto=format&fit=crop",
        "category": "Bluestone"
      }
    ],
    "description": "A hospitality project shaped around robust finishes and tonal consistency. The stone palette supports high traffic requirements while retaining premium character."
  },
  {
    "id": 4,
    "slug": "hawthorn-courtyard",
    "tags": [
      "Residential",
      "Landscape"
    ],
    "year": "2020",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop",
    "title": "Hawthorn Courtyard",
    "aspect": "aspect-[4/5]",
    "credits": {
      "builder": "Wattle Build",
      "architect": "Urban Habitat Studio",
      "landscaper": "Courtyard Works",
      "photographer": "June Park"
    },
    "gallery": [
      {
        "alt": "Wide shot of pool area",
        "src": "https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=2000&auto=format&fit=crop",
        "type": "full"
      },
      {
        "alt": "Detail of coping",
        "src": "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?q=80&w=1200&auto=format&fit=crop",
        "type": "half"
      },
      {
        "alt": "Top down view of pavers",
        "src": "https://images.unsplash.com/photo-1620626012053-93f2685048d6?q=80&w=1200&auto=format&fit=crop",
        "type": "half"
      },
      {
        "alt": "Exterior facade",
        "src": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2000&auto=format&fit=crop",
        "type": "full"
      }
    ],
    "category": "Residential",
    "gridArea": "right",
    "location": "Hawthorn, Victoria",
    "products": [
      {
        "name": "Ash Blend Sandstone",
        "slug": "ash-blend-sandstone",
        "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=800&auto=format&fit=crop",
        "category": "Sandstone"
      },
      {
        "name": "Linear Steppers",
        "slug": "linear-steppers",
        "image": "https://images.unsplash.com/photo-1620626012053-93f2685048d6?q=80&w=800&auto=format&fit=crop",
        "category": "Pavers"
      }
    ],
    "description": "A compact courtyard transformed through dimensional paving and soft-toned walling. The material strategy balances texture, drainage and tactile comfort."
  },
  {
    "id": 5,
    "slug": "sorrento-coastal-home",
    "tags": [
      "Residential",
      "Coastal"
    ],
    "year": "2024",
    "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1600&auto=format&fit=crop",
    "title": "Sorrento Coastal Home",
    "aspect": "aspect-[3/2]",
    "credits": {
      "builder": "Coastline Projects",
      "architect": "North Bay Studio",
      "landscaper": "Salt + Soil",
      "photographer": "Ari Holt"
    },
    "gallery": [
      {
        "alt": "Wide shot of pool area",
        "src": "https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=2000&auto=format&fit=crop",
        "type": "full"
      },
      {
        "alt": "Detail of coping",
        "src": "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?q=80&w=1200&auto=format&fit=crop",
        "type": "half"
      },
      {
        "alt": "Top down view of pavers",
        "src": "https://images.unsplash.com/photo-1620626012053-93f2685048d6?q=80&w=1200&auto=format&fit=crop",
        "type": "half"
      },
      {
        "alt": "Exterior facade",
        "src": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2000&auto=format&fit=crop",
        "type": "full"
      }
    ],
    "category": "Residential",
    "gridArea": "center",
    "location": "Sorrento, Victoria",
    "products": [
      {
        "name": "Marine Grade Limestone",
        "slug": "marine-grade-limestone",
        "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop",
        "category": "Limestone"
      },
      {
        "name": "Ribbed Coping",
        "slug": "ribbed-coping",
        "image": "https://images.unsplash.com/photo-1596178065887-1198b6148b2b?q=80&w=800&auto=format&fit=crop",
        "category": "Pool Coping"
      }
    ],
    "description": "A coastal residence that prioritizes durability in salt-air conditions. Finishes were selected for anti-slip performance and low-maintenance ageing."
  }
];
export const CMS_LEGACY_PAGES: LegacyPageContentMap = {
  "home": {
    "hero": {
      "text": "Natural stone, paving, pool coping and wall cladding advice from the Aushen showroom team.",
      "image": "/AushenShop.webp",
      "titleLines": [
        "Find your crafted",
        "architectural surfaces."
      ],
      "primaryHref": "/contact/",
      "primaryLabel": "Talk to a Stone Specialist",
      "secondaryHref": "/products/",
      "secondaryLabel": "Browse Products"
    },
    "brand": {
      "logo": "/AushenLogoLetterS.webp",
      "text": "At Aushen, we craft and curate only the best natural stone, architectural surfaces and outdoor furniture. We celebrate the imperfections and textural richness that can only be found in nature."
    },
    "services": {
      "items": [
        {
          "id": 1,
          "icon": "scan",
          "image": "https://images.unsplash.com/photo-1503387762-592deb58ef4e?q=80&w=1000&auto=format&fit=crop",
          "title": "Templating Service",
          "description": "Precision digital templating for perfect fits."
        },
        {
          "id": 2,
          "icon": "layers",
          "image": "/local-processing.jpg",
          "title": "Local Processing",
          "description": "Expert stone cutting and finishing in-house."
        },
        {
          "id": 3,
          "icon": "users",
          "image": "/design_consulation.png",
          "title": "Design Consultation",
          "description": "Collaborative sessions to bring vision to life."
        }
      ],
      "heading": "What we do",
      "introPrefix": "At Aushen, we do ",
      "introSuffix": " than just sell stone and tiles.",
      "introEmphasis": "more"
    },
    "accessories": {
      "text": "From sealing and maintenance to flush access covers and edge restraint, these are the supporting systems we pair with stone projects.",
      "items": {
        "hide": {
          "note": "Tile-in, paved, and recessed cover systems",
          "blurb": "Flush lids and covers that sit back into paving, tile, and pool surrounds.",
          "eyebrow": "Access covers"
        },
        "formboss": {
          "note": "Garden edging, planters, and install hardware",
          "blurb": "Steel edging and support details that sharpen the transition into landscape.",
          "eyebrow": "Edging systems"
        },
        "chemforce": {
          "note": "Protection, enhancement, and remedial cleaning",
          "blurb": "Sealers, enhancers, and cleaners for protecting and maintaining finished surfaces.",
          "eyebrow": "Stone care"
        }
      },
      "eyebrow": "Accessories",
      "heading": "The finishing pieces behind the stone.",
      "primaryHref": "/accessories/",
      "primaryLabel": "Explore Accessories",
      "secondaryHref": "/contact/",
      "secondaryLabel": "Talk to Us"
    },
    "creativeHub": {
      "images": [
        {
          "alt": "Creative Hub Showroom Area",
          "src": "/Homeowners.webp"
        },
        {
          "alt": "Material Selection Table",
          "src": "/Professionals.webp"
        }
      ],
      "marquee": "Our Space, Your Creative Hub",
      "audiences": [
        {
          "href": "/contact",
          "lead": "Feeling overwhelmed and stressed of your garden renovation?",
          "text": "Our experienced garden design team is here ready to guide you through the material selection process, ensuring your vision comes to life effortlessly.",
          "label": "Book A Consultation",
          "title": "Home Owners"
        },
        {
          "href": "/contact",
          "lead": "Need an inspiring space with all material samples ready to discuss the project with your clients?",
          "text": "Whether you are a builder, landscaper, or designer, we are committed to offering a space free of charge, with coffee on us.",
          "label": "Book The Space",
          "title": "Professionals"
        }
      ]
    },
    "projectShowcase": {
      "text": "Explore our curated portfolio of residential and commercial spaces, showcasing the timeless beauty of natural stone in harmony with modern architecture.",
      "image": "/Application001.webp",
      "linkHref": "/projects",
      "linkLabel": "Explore More",
      "titlePrefix": "Get Inspired by",
      "titleSuffix": "Projects",
      "titleEmphasis": "Our Favorite"
    }
  },
  "services": {
    "cta": {
      "text": "Let's discuss your project over coffee.",
      "heading": "Ready to begin?",
      "primaryHref": "/contact",
      "primaryLabel": "Contact Us",
      "secondaryHref": "/contact",
      "secondaryLabel": "Visit Showroom"
    },
    "hero": {
      "text": "We don't just supply natural stone. We craft, customize, and curate it to fit your vision perfectly.",
      "title": "Beyond",
      "eyebrow": "Our Expertise",
      "emphasis": "The Stone"
    },
    "logistics": {
      "items": [
        {
          "icon": "network",
          "text": "We don't install, but we know who does it best. Access our curated list of verified professionals.",
          "title": "Trusted Installer Network"
        },
        {
          "icon": "logistics",
          "text": "Tight access? No problem. We coordinate crane trucks to ensure your stone is delivered safely.",
          "title": "Flexible Logistics"
        },
        {
          "icon": "support",
          "text": "Detailed advice on sealing, cleaning, and maintaining your stone for decades to come.",
          "title": "After-Care Support"
        }
      ],
      "heading": "Seamless Delivery",
      "stepLabel": "Step 03 — Final Mile"
    },
    "fabrication": {
      "items": [
        {
          "id": "profiling",
          "image": "/task-a-2026-02-24/svc-profiling.webp",
          "title": "Edge Profiling",
          "features": [
            "Bullnose & Pencil Edge",
            "Drop Face Coping",
            "Mitred Aprons"
          ],
          "description": "From classic pencil rounds to complex drop-face coping. We shape the stone to fit your design language, ensuring every edge is smooth, safe, and aesthetically perfect."
        },
        {
          "id": "curved",
          "image": "/task-a-2026-02-24/svc-curved.webp",
          "title": "Curved Cutting",
          "features": [
            "Radius Cutting",
            "Template Matching",
            "Zero-tolerance Fit"
          ],
          "description": "Standard pavers don't fit curved pools. Our specialized waterjet and bridge saw technology allows us to cut precise radii, creating a seamless flow for organic shapes."
        },
        {
          "id": "bespoke",
          "image": "/task-a-2026-02-24/svc-bespoke.webp",
          "title": "Bespoke Custom",
          "features": [
            "Core Drilling",
            "Skimmer Box Lids",
            "Custom Grates"
          ],
          "description": "Need a hole for a light fixture? A specific drain cutout? Or a custom-engraved piece? We handle all technical modifications in-house to save you time on site."
        }
      ],
      "eyebrow": "The Workshop",
      "heading": "Precision Fabrication"
    },
    "consultation": {
      "href": "/contact",
      "text": "Navigating natural stone options can be overwhelming. Our experienced team is here to guide you through color palettes, finishes, and technical suitability for your specific project.",
      "image": "/task-a-2026-02-24/svc-consultation.webp",
      "label": "Book A Consultation",
      "quote": "Bring your plans, the coffee is on us.",
      "eyebrow": "Design Consultation",
      "heading": "Not sure where to start?",
      "imageAlt": "Showroom Consultation"
    }
  },
  "about": {
    "hero": {
      "text": "We are not just suppliers. We are curators of geology, bridging the gap between the ancient quarry and the modern home.",
      "image": "/task-a-2026-02-24/about-hero-quarry.webp",
      "title": "The Stone",
      "eyebrow": "Since 2003",
      "emphasis": "Keeper.",
      "scrollLabel": "Scroll the timeline"
    },
    "timeline": [
      {
        "desc": "It started with a trip to Europe's ancient quarries. We realized that true quality can't be ordered from a catalog; it must be touched.",
        "year": "The Origin",
        "align": "left",
        "image": "/task-a-2026-02-24/about-origin-sourcing.webp",
        "title": "Global Sourcing"
      },
      {
        "desc": "We established our strict selection criteria early on. Consistency in tone, durability in texture. If we wouldn't use it, we don't sell it.",
        "year": "The Standard",
        "align": "right",
        "image": "/task-a-2026-02-24/about-standard-qc.webp",
        "title": "The 10% Rule"
      },
      {
        "desc": "We planted our roots in Melbourne's Bayside. A showroom built not to display products, but to spark conversations.",
        "year": "The Place",
        "align": "left",
        "image": "/task-a-2026-02-24/about-place-showroom.webp",
        "title": "Bayside Roots"
      }
    ],
    "manifesto": {
      "label": "Our Philosophy",
      "quote": "We reject 90% of what we find. Not out of arrogance, but out of respect for the home you are building."
    },
    "signature": {
      "quote": "We invite you to experience the difference yourself."
    }
  }
};
export const CMS_SITE_CONTENT_SYNCED = true;
