// Generated by scripts/sync-cms-data.ts. Do not edit manually.
import type { ProductOverride } from "@/types/product";
export const CMS_PRODUCT_OVERRIDES: Record<string, ProductOverride> = {
  "antarctica": {
    "imageUrl": "/product-photos/antarctica-01.webp",
    "imageUrls": [
      "/product-photos/antarctica-01.webp",
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/fe60831b-5296-42d8-aa66-9e06c88919a6-marble-antarctica-white-application-4.jpg",
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/ccf6de70-b6c2-48b6-92da-b62af573e27e-marble-antarctica-white-application-2.jpg",
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/e3438ce7-2901-46d0-9a9c-79f7f0c978c5-marble-antarctica-white-application-6.jpg",
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/2d8b9d90-963e-4aba-8ed7-f0345f6ef805-marble-antarctica-white-application-7.jpg"
    ],
    "applicationImageUrls": [
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/fe60831b-5296-42d8-aa66-9e06c88919a6-marble-antarctica-white-application-4.jpg",
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/ccf6de70-b6c2-48b6-92da-b62af573e27e-marble-antarctica-white-application-2.jpg",
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/e3438ce7-2901-46d0-9a9c-79f7f0c978c5-marble-antarctica-white-application-6.jpg",
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/2d8b9d90-963e-4aba-8ed7-f0345f6ef805-marble-antarctica-white-application-7.jpg"
    ],
    "description": ""
  },
  "atlantic-grey": {
    "imageUrl": "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/5ac9bff7-a078-490c-be8e-2b209a6b692a-atlantic-grey.jpg",
    "imageUrls": [
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/5ac9bff7-a078-490c-be8e-2b209a6b692a-atlantic-grey.jpg",
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/31572470-4c81-4fcd-8f84-dad53b749280--20260715104426-17-14.jpg",
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/cc302ddd-1280-4726-9088-5335239ff7b1--20260715104418-15-14.jpg",
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/f40c9e82-72c1-43c6-97b8-45cce428b7f9--20260715104420-16-14.jpg",
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/3e2c1f50-52f5-4b3a-bfae-532de8a5ceab-atlantic-grey-application.jpg",
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/d20b6176-15a4-42f7-b686-ac40306525e9--20260715104416-14-14.jpg"
    ],
    "applicationImageUrls": [
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/31572470-4c81-4fcd-8f84-dad53b749280--20260715104426-17-14.jpg",
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/cc302ddd-1280-4726-9088-5335239ff7b1--20260715104418-15-14.jpg",
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/f40c9e82-72c1-43c6-97b8-45cce428b7f9--20260715104420-16-14.jpg",
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/3e2c1f50-52f5-4b3a-bfae-532de8a5ceab-atlantic-grey-application.jpg",
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/application/d20b6176-15a4-42f7-b686-ac40306525e9--20260715104416-14-14.jpg"
    ],
    "description": ""
  },
  "angola-black": {
    "imageUrl": "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/32a96e43-62c7-4c66-b885-ba5344a21959-angola-black.jpg",
    "imageUrls": [
      "https://mwxkwusmisegsictizuz.supabase.co/storage/v1/object/public/cms-media/products/32a96e43-62c7-4c66-b885-ba5344a21959-angola-black.jpg"
    ],
    "applicationImageUrls": [],
    "description": ""
  },
  "dark-bluestone": {
    "imageUrl": "/product-photos/dark-bluestone-01.webp",
    "imageUrls": [
      "/product-photos/dark-bluestone-01.webp"
    ],
    "applicationImageUrls": []
  },
  "beige-travertine-sai": {
    "imageUrl": "/product-photos/beige-travertine-sai-01.webp",
    "imageUrls": [
      "/product-photos/beige-travertine-sai-01.webp"
    ],
    "applicationImageUrls": []
  },
  "belgium-blue": {
    "imageUrl": "/product-photos/belgium-blue-01.webp",
    "imageUrls": [
      "/product-photos/belgium-blue-01.webp"
    ],
    "applicationImageUrls": []
  },
  "beloka": {
    "imageUrl": "/product-photos/beloka-01.webp",
    "imageUrls": [
      "/product-photos/beloka-01.webp"
    ],
    "applicationImageUrls": []
  },
  "bianca-chiaro": {
    "imageUrl": "/product-photos/bianca-chiaro-01.webp",
    "imageUrls": [
      "/product-photos/bianca-chiaro-01.webp"
    ],
    "applicationImageUrls": []
  },
  "black-granite": {
    "imageUrl": "/product-photos/black-granite-01.webp",
    "imageUrls": [
      "/product-photos/black-granite-01.webp"
    ],
    "applicationImageUrls": []
  },
  "black-ochre-blend": {
    "imageUrl": "/product-photos/black-ochre-blend-01.webp",
    "imageUrls": [
      "/product-photos/black-ochre-blend-01.webp"
    ],
    "applicationImageUrls": []
  },
  "blue-ridge": {
    "imageUrl": "/product-photos/blue-ridge-01.webp",
    "imageUrls": [
      "/product-photos/blue-ridge-01.webp"
    ],
    "applicationImageUrls": []
  },
  "blueocean": {
    "imageUrl": "/product-photos/blueocean-01.webp",
    "imageUrls": [
      "/product-photos/blueocean-01.webp"
    ],
    "applicationImageUrls": []
  },
  "monte-carlo": {
    "imageUrl": "/product-photos/monte-carlo-01.webp",
    "imageUrls": [
      "/product-photos/monte-carlo-01.webp"
    ],
    "applicationImageUrls": []
  },
  "blueocean-honed": {
    "imageUrl": "/product-photos/blueocean-honed-01.webp",
    "imageUrls": [
      "/product-photos/blueocean-honed-01.webp"
    ],
    "applicationImageUrls": [],
    "description": "BlueOcean Honed offers the cooler BlueOcean bluestone palette with a smoother, more architectural face for refined paving, coping, and feature applications."
  },
  "buffalo": {
    "imageUrl": "/product-photos/buffalo-01.webp",
    "imageUrls": [
      "/product-photos/buffalo-01.webp"
    ],
    "applicationImageUrls": []
  },
  "charcoal-quartz": {
    "imageUrl": "/product-photos/charcoal-quartz-01.webp",
    "imageUrls": [
      "/product-photos/charcoal-quartz-01.webp"
    ],
    "applicationImageUrls": []
  },
  "charlotte": {
    "imageUrl": "/product-photos/charlotte-01.webp",
    "imageUrls": [
      "/product-photos/charlotte-01.webp"
    ],
    "applicationImageUrls": []
  },
  "classic-travertine-sai": {
    "imageUrl": "/product-photos/classic-travertine-sai-01.webp",
    "imageUrls": [
      "/product-photos/classic-travertine-sai-01.webp"
    ],
    "applicationImageUrls": []
  },
  "crema-siena": {
    "imageUrl": "/product-photos/crema-siena-01.webp",
    "imageUrls": [
      "/product-photos/crema-siena-01.webp"
    ],
    "applicationImageUrls": []
  },
  "frozen-blue": {
    "imageUrl": "/product-photos/frozen-blue-01.webp",
    "imageUrls": [
      "/product-photos/frozen-blue-01.webp"
    ],
    "applicationImageUrls": []
  },
  "glacier": {
    "imageUrl": "/product-photos/glacier-01.webp",
    "imageUrls": [
      "/product-photos/glacier-01.webp"
    ],
    "applicationImageUrls": []
  },
  "grey-apricot": {
    "imageUrl": "/product-photos/grey-apricot-01.webp",
    "imageUrls": [
      "/product-photos/grey-apricot-01.webp"
    ],
    "applicationImageUrls": []
  },
  "grey-limestone": {
    "imageUrl": "/product-photos/grey-limestone-01.webp",
    "imageUrls": [
      "/product-photos/grey-limestone-01.webp"
    ],
    "applicationImageUrls": []
  },
  "grey-permeable-paver": {
    "imageUrl": "/product-photos/grey-permeable-paver-01.webp",
    "imageUrls": [
      "/product-photos/grey-permeable-paver-01.webp"
    ],
    "applicationImageUrls": []
  },
  "grigio-storm": {
    "imageUrl": "/product-photos/grigio-storm-01.webp",
    "imageUrls": [
      "/product-photos/grigio-storm-01.webp"
    ],
    "applicationImageUrls": []
  },
  "honey-limestone": {
    "imageUrl": "/product-photos/honey-limestone-01.webp",
    "imageUrls": [
      "/product-photos/honey-limestone-01.webp"
    ],
    "applicationImageUrls": []
  },
  "hotham": {
    "imageUrl": "/product-photos/hotham-01.webp",
    "imageUrls": [
      "/product-photos/hotham-01.webp"
    ],
    "applicationImageUrls": []
  },
  "jamieson": {
    "imageUrl": "/product-photos/jamieson-01.webp",
    "imageUrls": [
      "/product-photos/jamieson-01.webp"
    ],
    "applicationImageUrls": []
  },
  "jasper": {
    "imageUrl": "/product-photos/jasper-01.webp",
    "imageUrls": [
      "/product-photos/jasper-01.webp"
    ],
    "applicationImageUrls": []
  },
  "kakadu": {
    "imageUrl": "/product-photos/kakadu-01.webp",
    "imageUrls": [
      "/product-photos/kakadu-01.webp"
    ],
    "applicationImageUrls": []
  },
  "ken-black": {
    "imageUrl": "/product-photos/ken-black-01.webp",
    "imageUrls": [
      "/product-photos/ken-black-01.webp"
    ],
    "applicationImageUrls": []
  },
  "lux-black": {
    "imageUrl": "/product-photos/lux-black-01.webp",
    "imageUrls": [
      "/product-photos/lux-black-01.webp"
    ],
    "applicationImageUrls": []
  },
  "moonlight-grey": {
    "imageUrl": "/product-photos/moonlight-grey-01.webp",
    "imageUrls": [
      "/product-photos/moonlight-grey-01.webp"
    ],
    "applicationImageUrls": []
  },
  "multicolor-ochre-blend": {
    "imageUrl": "/product-photos/multicolor-ochre-blend-01.webp",
    "imageUrls": [
      "/product-photos/multicolor-ochre-blend-01.webp"
    ],
    "applicationImageUrls": []
  },
  "new-grey": {
    "imageUrl": "/product-photos/new-grey-01.webp",
    "imageUrls": [
      "/product-photos/new-grey-01.webp"
    ],
    "applicationImageUrls": []
  },
  "nimbus-white": {
    "imageUrl": "/product-photos/nimbus-white-01.webp",
    "imageUrls": [
      "/product-photos/nimbus-white-01.webp"
    ],
    "applicationImageUrls": []
  },
  "pearl-grey": {
    "imageUrl": "/product-photos/pearl-grey-01.webp",
    "imageUrls": [
      "/product-photos/pearl-grey-01.webp"
    ],
    "applicationImageUrls": []
  },
  "philadelphia-silver-travertine-cross-cut-tumbled": {
    "imageUrl": "/product-photos/philadelphia-silver-travertine-cross-cut-tumbled-01.webp",
    "imageUrls": [
      "/product-photos/philadelphia-silver-travertine-cross-cut-tumbled-01.webp"
    ],
    "applicationImageUrls": []
  },
  "philadelphia-silver-travertine-vien-cut": {
    "imageUrl": "/product-photos/philadelphia-silver-travertine-vien-cut-01.webp",
    "imageUrls": [
      "/product-photos/philadelphia-silver-travertine-vien-cut-01.webp"
    ],
    "applicationImageUrls": []
  },
  "premium-classic-travertine-artma": {
    "imageUrl": "/product-photos/premium-classic-travertine-artma-01.webp",
    "imageUrls": [
      "/product-photos/premium-classic-travertine-artma-01.webp"
    ],
    "applicationImageUrls": []
  },
  "red-ochre-blend": {
    "imageUrl": "/product-photos/red-ochre-blend-01.webp",
    "imageUrls": [
      "/product-photos/red-ochre-blend-01.webp"
    ],
    "applicationImageUrls": []
  },
  "reefstone-creamy-white": {
    "imageUrl": "/product-photos/reefstone-creamy-white-01.webp",
    "imageUrls": [
      "/product-photos/reefstone-creamy-white-01.webp"
    ],
    "applicationImageUrls": []
  },
  "reefstone-dark-grey": {
    "imageUrl": "/product-photos/reefstone-dark-grey-01.webp",
    "imageUrls": [
      "/product-photos/reefstone-dark-grey-01.webp"
    ],
    "applicationImageUrls": []
  },
  "reefstone-neutral-grey": {
    "imageUrl": "/product-photos/reefstone-neutral-grey-01.webp",
    "imageUrls": [
      "/product-photos/reefstone-neutral-grey-01.webp"
    ],
    "applicationImageUrls": []
  },
  "reefstone-warm-grey": {
    "imageUrl": "/product-photos/reefstone-warm-grey-01.webp",
    "imageUrls": [
      "/product-photos/reefstone-warm-grey-01.webp"
    ],
    "applicationImageUrls": []
  },
  "roman": {
    "imageUrl": "/product-photos/roman-01.webp",
    "imageUrls": [
      "/product-photos/roman-01.webp"
    ],
    "applicationImageUrls": []
  },
  "sahara-beige": {
    "imageUrl": "/product-photos/sahara-beige-01.webp",
    "imageUrls": [
      "/product-photos/sahara-beige-01.webp"
    ],
    "applicationImageUrls": []
  },
  "sandy-beige": {
    "imageUrl": "/product-photos/sandy-beige-01.webp",
    "imageUrls": [
      "/product-photos/sandy-beige-01.webp"
    ],
    "applicationImageUrls": []
  },
  "seagrass": {
    "imageUrl": "/product-photos/seagrass-01.webp",
    "imageUrls": [
      "/product-photos/seagrass-01.webp"
    ],
    "applicationImageUrls": []
  },
  "sesame-white": {
    "imageUrl": "/product-photos/sesame-white-01.webp",
    "imageUrls": [
      "/product-photos/sesame-white-01.webp"
    ],
    "applicationImageUrls": []
  },
  "siena-earth": {
    "imageUrl": "/product-photos/siena-earth-01.webp",
    "imageUrls": [
      "/product-photos/siena-earth-01.webp"
    ],
    "applicationImageUrls": []
  },
  "siena-grey": {
    "imageUrl": "/product-photos/siena-grey-01.webp",
    "imageUrls": [
      "/product-photos/siena-grey-01.webp"
    ],
    "applicationImageUrls": []
  },
  "siena-pearl": {
    "imageUrl": "/product-photos/siena-pearl-01.webp",
    "imageUrls": [
      "/product-photos/siena-pearl-01.webp"
    ],
    "applicationImageUrls": []
  },
  "siena-taupe": {
    "imageUrl": "/product-photos/siena-taupe-01.webp",
    "imageUrls": [
      "/product-photos/siena-taupe-01.webp"
    ],
    "applicationImageUrls": []
  },
  "silver-ash": {
    "imageUrl": "/product-photos/silver-ash-01.webp",
    "imageUrls": [
      "/product-photos/silver-ash-01.webp"
    ],
    "applicationImageUrls": []
  },
  "silver-lighht-travertine-veincut": {
    "imageUrl": "/product-photos/silver-lighht-travertine-veincut-01.webp",
    "imageUrls": [
      "/product-photos/silver-lighht-travertine-veincut-01.webp"
    ],
    "applicationImageUrls": []
  },
  "silver-travertine-artma": {
    "imageUrl": "/product-photos/silver-travertine-artma-01.webp",
    "imageUrls": [
      "/product-photos/silver-travertine-artma-01.webp"
    ],
    "applicationImageUrls": []
  },
  "steal-blue": {
    "imageUrl": "/product-photos/steal-blue-01.webp",
    "imageUrls": [
      "/product-photos/steal-blue-01.webp"
    ],
    "applicationImageUrls": []
  },
  "stormy-grey": {
    "imageUrl": "/product-photos/stormy-grey-01.webp",
    "imageUrls": [
      "/product-photos/stormy-grey-01.webp"
    ],
    "applicationImageUrls": []
  },
  "toros-black": {
    "imageUrl": "/product-photos/toros-black-01.webp",
    "imageUrls": [
      "/product-photos/toros-black-01.webp"
    ],
    "applicationImageUrls": []
  },
  "tundra-blue": {
    "imageUrl": "/product-photos/tundra-blue-01.webp",
    "imageUrls": [
      "/product-photos/tundra-blue-01.webp"
    ],
    "applicationImageUrls": []
  },
  "antline": {
    "imageUrl": "/product-photos/antline-01.webp",
    "imageUrls": [
      "/product-photos/antline-01.webp"
    ],
    "applicationImageUrls": []
  },
  "tuscany-classic": {
    "imageUrl": "/product-photos/tuscany-classic-01.webp",
    "imageUrls": [
      "/product-photos/tuscany-classic-01.webp"
    ],
    "applicationImageUrls": []
  },
  "tuscany-white": {
    "imageUrl": "/product-photos/tuscany-white-01.webp",
    "imageUrls": [
      "/product-photos/tuscany-white-01.webp"
    ],
    "applicationImageUrls": []
  },
  "vintage-oyster": {
    "imageUrl": "/product-photos/vintage-oyster-01.webp",
    "imageUrls": [
      "/product-photos/vintage-oyster-01.webp"
    ],
    "applicationImageUrls": []
  },
  "white-ochre-blend": {
    "imageUrl": "/product-photos/white-ochre-blend-01.webp",
    "imageUrls": [
      "/product-photos/white-ochre-blend-01.webp"
    ],
    "applicationImageUrls": []
  },
  "wilderness-grey": {
    "imageUrl": "/product-photos/wilderness-grey-01.webp",
    "imageUrls": [
      "/product-photos/wilderness-grey-01.webp"
    ],
    "applicationImageUrls": []
  },
  "zen-grey": {
    "imageUrl": "/product-photos/zen-grey-01.webp",
    "imageUrls": [
      "/product-photos/zen-grey-01.webp"
    ],
    "applicationImageUrls": []
  },
  "tundra-grey": {
    "imageUrl": "/product-photos/tundra-grey-01.webp",
    "imageUrls": [
      "/product-photos/tundra-grey-01.webp"
    ],
    "applicationImageUrls": []
  },
  "ash-grey": {
    "imageUrl": "/product-photos/ash-grey-01.webp",
    "imageUrls": [
      "/product-photos/ash-grey-01.webp"
    ],
    "applicationImageUrls": []
  },
  "barwon": {
    "imageUrl": "/product-photos/barwon-01.webp",
    "imageUrls": [
      "/product-photos/barwon-01.webp"
    ],
    "applicationImageUrls": []
  },
  "beachport": {
    "imageUrl": "/product-photos/beachport-01.webp",
    "imageUrls": [
      "/product-photos/beachport-01.webp"
    ],
    "applicationImageUrls": []
  }
};
