// Generated by scripts/sync-cms-data.ts. Do not edit manually.
import type { SeoLandingPage } from "@/types/seoLandingPage";

export const CMS_SEO_LANDING_PAGES: SeoLandingPage[] = [];
export const CMS_SEO_LANDING_PAGES_SYNCED = false;
