// This file is auto-generated by scripts/prepare-product-photos.py. Do not edit.

export const PRODUCT_IMAGE_GALLERIES: Record<string, string[]> = {
  "antarctica": [
    "/product-photos/antarctica-01.webp"
  ],
  "antline": [
    "/product-photos/antline-01.webp"
  ],
  "ash-grey": [
    "/product-photos/ash-grey-01.webp"
  ],
  "atlantic-grey": [
    "/product-photos/atlantic-grey-01.webp"
  ],
  "beachport": [
    "/product-photos/beachport-01.webp"
  ],
  "beige-travertine-sai": [
    "/product-photos/beige-travertine-sai-01.webp"
  ],
  "belgium-blue": [
    "/product-photos/belgium-blue-01.webp"
  ],
  "beloka": [
    "/product-photos/beloka-01.webp"
  ],
  "bianca-chiaro": [
    "/product-photos/bianca-chiaro-01.webp"
  ],
  "black-ochre-blend": [
    "/product-photos/black-ochre-blend-01.webp"
  ],
  "blue-ridge": [
    "/product-photos/blue-ridge-01.webp"
  ],
  "blueocean": [
    "/product-photos/blueocean-01.webp",
    "/product-photos/blueocean-02.webp"
  ],
  "buffalo": [
    "/product-photos/buffalo-01.webp"
  ],
  "charlotte": [
    "/product-photos/charlotte-01.webp"
  ],
  "classic-travertine-sai": [
    "/product-photos/classic-travertine-sai-01.webp",
    "/product-photos/classic-travertine-sai-02.webp",
    "/product-photos/classic-travertine-sai-03.webp",
    "/product-photos/classic-travertine-sai-04.webp",
    "/product-photos/classic-travertine-sai-05.webp"
  ],
  "crema-siena": [
    "/product-photos/crema-siena-01.webp"
  ],
  "frozen-blue": [
    "/product-photos/frozen-blue-01.webp"
  ],
  "glacier": [
    "/product-photos/glacier-01.webp"
  ],
  "grey-apricot": [
    "/product-photos/grey-apricot-01.webp"
  ],
  "grey-permeable-paver": [
    "/product-photos/grey-permeable-paver-01.webp"
  ],
  "honey-limestone": [
    "/product-photos/honey-limestone-01.webp"
  ],
  "hotham": [
    "/product-photos/hotham-01.webp"
  ],
  "jamieson": [
    "/product-photos/jamieson-01.webp"
  ],
  "ken-black": [
    "/product-photos/ken-black-01.webp"
  ],
  "lux-black": [
    "/product-photos/lux-black-01.webp"
  ],
  "moonlight-grey": [
    "/product-photos/moonlight-grey-01.webp"
  ],
  "multicolor-ochre-blend": [
    "/product-photos/multicolor-ochre-blend-01.webp"
  ],
  "new-grey": [
    "/product-photos/new-grey-01.webp"
  ],
  "nimbus-white": [
    "/product-photos/nimbus-white-01.webp"
  ],
  "pearl-grey": [
    "/product-photos/pearl-grey-01.webp"
  ],
  "philadelphia-silver-travertine-vien-cut": [
    "/product-photos/philadelphia-silver-travertine-vien-cut-01.webp",
    "/product-photos/philadelphia-silver-travertine-vien-cut-02.webp"
  ],
  "premium-classic-travertine-artma": [
    "/product-photos/premium-classic-travertine-artma-01.webp"
  ],
  "red-ochre-blend": [
    "/product-photos/red-ochre-blend-01.webp"
  ],
  "reefstone-creamy-white": [
    "/product-photos/reefstone-creamy-white-01.webp"
  ],
  "reefstone-dark-grey": [
    "/product-photos/reefstone-dark-grey-01.webp"
  ],
  "reefstone-neutral-grey": [
    "/product-photos/reefstone-neutral-grey-01.webp"
  ],
  "reefstone-warm-grey": [
    "/product-photos/reefstone-warm-grey-01.webp"
  ],
  "seagrass": [
    "/product-photos/seagrass-01.webp"
  ],
  "sesame-white": [
    "/product-photos/sesame-white-01.webp"
  ],
  "siena-earth": [
    "/product-photos/siena-earth-01.webp"
  ],
  "siena-grey": [
    "/product-photos/siena-grey-01.webp",
    "/product-photos/siena-grey-02.webp"
  ],
  "siena-pearl": [
    "/product-photos/siena-pearl-01.webp"
  ],
  "siena-taupe": [
    "/product-photos/siena-taupe-01.webp"
  ],
  "silver-ash": [
    "/product-photos/silver-ash-01.webp"
  ],
  "silver-lighht-travertine-veincut": [
    "/product-photos/silver-lighht-travertine-veincut-01.webp"
  ],
  "silver-travertine-artma": [
    "/product-photos/silver-travertine-artma-01.webp",
    "/product-photos/silver-travertine-artma-02.webp"
  ],
  "steal-blue": [
    "/product-photos/steal-blue-01.webp"
  ],
  "stormy-grey": [
    "/product-photos/stormy-grey-01.webp",
    "/product-photos/stormy-grey-02.webp"
  ],
  "toros-black": [
    "/product-photos/toros-black-01.webp"
  ],
  "tundra-blue": [
    "/product-photos/tundra-blue-01.webp"
  ],
  "tundra-grey": [
    "/product-photos/tundra-grey-01.webp"
  ],
  "white-ochre-blend": [
    "/product-photos/white-ochre-blend-01.webp"
  ],
  "wilderness-grey": [
    "/product-photos/wilderness-grey-01.webp"
  ],
  "zen-grey": [
    "/product-photos/zen-grey-01.webp"
  ]
};

export const PRODUCT_COVER_IMAGES: Record<string, string> = {
  "antarctica": "/product-photos/antarctica-01.webp",
  "antline": "/product-photos/antline-01.webp",
  "ash-grey": "/product-photos/ash-grey-01.webp",
  "atlantic-grey": "/product-photos/atlantic-grey-01.webp",
  "beachport": "/product-photos/beachport-01.webp",
  "beige-travertine-sai": "/product-photos/beige-travertine-sai-01.webp",
  "belgium-blue": "/product-photos/belgium-blue-01.webp",
  "beloka": "/product-photos/beloka-01.webp",
  "bianca-chiaro": "/product-photos/bianca-chiaro-01.webp",
  "black-ochre-blend": "/product-photos/black-ochre-blend-01.webp",
  "blue-ridge": "/product-photos/blue-ridge-01.webp",
  "blueocean": "/product-photos/blueocean-01.webp",
  "buffalo": "/product-photos/buffalo-01.webp",
  "charlotte": "/product-photos/charlotte-01.webp",
  "classic-travertine-sai": "/product-photos/classic-travertine-sai-01.webp",
  "crema-siena": "/product-photos/crema-siena-01.webp",
  "frozen-blue": "/product-photos/frozen-blue-01.webp",
  "glacier": "/product-photos/glacier-01.webp",
  "grey-apricot": "/product-photos/grey-apricot-01.webp",
  "grey-permeable-paver": "/product-photos/grey-permeable-paver-01.webp",
  "honey-limestone": "/product-photos/honey-limestone-01.webp",
  "hotham": "/product-photos/hotham-01.webp",
  "jamieson": "/product-photos/jamieson-01.webp",
  "ken-black": "/product-photos/ken-black-01.webp",
  "lux-black": "/product-photos/lux-black-01.webp",
  "moonlight-grey": "/product-photos/moonlight-grey-01.webp",
  "multicolor-ochre-blend": "/product-photos/multicolor-ochre-blend-01.webp",
  "new-grey": "/product-photos/new-grey-01.webp",
  "nimbus-white": "/product-photos/nimbus-white-01.webp",
  "pearl-grey": "/product-photos/pearl-grey-01.webp",
  "philadelphia-silver-travertine-vien-cut": "/product-photos/philadelphia-silver-travertine-vien-cut-01.webp",
  "premium-classic-travertine-artma": "/product-photos/premium-classic-travertine-artma-01.webp",
  "red-ochre-blend": "/product-photos/red-ochre-blend-01.webp",
  "reefstone-creamy-white": "/product-photos/reefstone-creamy-white-01.webp",
  "reefstone-dark-grey": "/product-photos/reefstone-dark-grey-01.webp",
  "reefstone-neutral-grey": "/product-photos/reefstone-neutral-grey-01.webp",
  "reefstone-warm-grey": "/product-photos/reefstone-warm-grey-01.webp",
  "seagrass": "/product-photos/seagrass-01.webp",
  "sesame-white": "/product-photos/sesame-white-01.webp",
  "siena-earth": "/product-photos/siena-earth-01.webp",
  "siena-grey": "/product-photos/siena-grey-01.webp",
  "siena-pearl": "/product-photos/siena-pearl-01.webp",
  "siena-taupe": "/product-photos/siena-taupe-01.webp",
  "silver-ash": "/product-photos/silver-ash-01.webp",
  "silver-lighht-travertine-veincut": "/product-photos/silver-lighht-travertine-veincut-01.webp",
  "silver-travertine-artma": "/product-photos/silver-travertine-artma-01.webp",
  "steal-blue": "/product-photos/steal-blue-01.webp",
  "stormy-grey": "/product-photos/stormy-grey-01.webp",
  "toros-black": "/product-photos/toros-black-01.webp",
  "tundra-blue": "/product-photos/tundra-blue-01.webp",
  "tundra-grey": "/product-photos/tundra-grey-01.webp",
  "white-ochre-blend": "/product-photos/white-ochre-blend-01.webp",
  "wilderness-grey": "/product-photos/wilderness-grey-01.webp",
  "zen-grey": "/product-photos/zen-grey-01.webp"
};
